### ISSUE TITLE
A few suggestions to the CSS code formatting and layout.

### ISSUE THREAD

**Issue by josephtkim** [JorgvanderSchaaf/Colmar-new#6]
There are a few suggestions that you might want to make to possible improve the readability of your CSS code. Try to reduce the number of empty lines in the code. You usually just need a single empty line between each selector, like

```css
body {
  font-family: 'Raleway', sans-serif;
  font-size: 16px;
  line-height: 1;
  color: DimGray;
  margin: 0;
}

.center {
  text-align: center;
}

.container, .flex {
  display: flex;
}
```
In addition, try to avoid having unused code like 
https://github.com/JorgvanderSchaaf/Colmar-new/blob/master/resources/css/style.css#L159-L162
https://github.com/JorgvanderSchaaf/Colmar-new/blob/master/resources/css/style.css#L227-L229

and try to stay consistent with the formatting that is used throughout all of the code.
